fail_fast: true

repos:
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
    -   id: black
        name: "Black format checker"
        args: ["--check"]
        language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: "Imports order checker"
        args: ["--check"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        name: "Python types analyzer"
        args: ["src", "tests"]
        language: python
        pass_filenames: false
