fail_fast: true

repos:
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
        name: "Black format checker"
        args: ["--check"]
        language_version: python3

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        name: "Python types analyzer (source)"
        args: ["src"]
        language: python
        pass_filenames: false
    -   id: mypy
        name: "Python types analyzer (tests)"
        args: ["tests"]
        language: python
        pass_filenames: false
